Repository JNU-econovation/git-2-Alzzang-and-musclezzang, pull requests merged in 2023-12, with the labels that each got.

#4 [Docs] answer2 5-7번 답 작성
  answer2.md
Labels: Muscle zzang

#2 [Docs] answer1 5~10 답 작성
  answer1.md
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, Muscle zzang

#3 [Docs] answer2 1~4 답 작성
  answer2.md
Labels: documentation
